services:
  db:
    image: postgres:16.1
    container_name: belts-postgres
    environment:
      POSTGRES_DB: "belts_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
   