# Generated by Django 5.2.11 on 2026-04-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_alter_orderitem_options_and_more'),
        ('product', '0003_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=30, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='test', max_length=120, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, max_length=30, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default='test', max_length=30, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='intercom',
            field=models.CharField(blank=True, max_length=30, verbose_name='Домофон'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='test', max_length=30, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Получатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='test', max_length=255, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
